server:
  port: 8000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloudcampus-edu
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    #腾讯云
    url: jdbc:mysql://49.234.142.138:8706/saxd?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Mysql_321
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    #食安新都 223.247.210.87 3306 root SAxd13578@#Slave

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.rh.cloudcampus.edu.dto

logging:
  config: classpath:log4j2.xml