server:
  port: 8010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: order-path
          uri: lb://cloudcampus-order
          predicates:
            - Path=/order/{segment}
          filters:
            - SetPath=/{segment}
        - id: shopping-path
          uri: lb://cloudcampus-shopping
          predicates:
            - Path=/shopping/{segment}
          filters:
            - SetPath=/{segment}
        - id: takout-path
          uri: lb://cloudcampus-take-out
          predicates:
            - Path=/takeout/{segment}
          filters:
            - SetPath=/{segment}
        - id: user-path
          uri: lb://cloudcampus-user
          predicates:
            - Path=/user/{segment}
          filters:
            - SetPath=/test/{segment}
