server:
  port: 8001

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: consumer
#          uri: lb://consumer
#          predicates:
#            - Path=/mytest11/{segment}
#          filters:
#            - RewritePath=/consumer(?<segment>/?.*), $\{segment}
#            - SetPath=/{segment}
#        - id: provider222
#          uri: lb://provider
#          predicates:
#            - Path=/proxxx/**
#          filters:
#            - RewritePath=/provider(?<segment>/?.*), $\{segment}
        - id: setpath_route
          uri: lb://provider
          predicates:
            - Path=/mytest/{segment}
          filters:
            - SetPath=/{segment}
